### ISSUE TITLE
Master does not publish the docs to gh-pages any more

### ISSUE THREAD

**Issue by thengl** [Envirometrix/PredictiveSoilMapping#10]
Master does not deploy output docs to gh-pages any more hence the HTML version is now out of date. Probably some setting problem in: https://github.com/Envirometrix/PredictiveSoilMapping/blob/master/deploy.sh

**Comment by thengl** [comment]
Now fixed. Thanks @Nowosad

**Comment by Nowosad** [comment]
:+1: Great!
